// GENERATED — do not edit; run `bun contracts/spec/gen-rust.ts`.
export type * from "./numeric-microts.ts";
export type StyleClass = string & { readonly __style?: true };
export type Cap<T extends string | readonly unknown[], N extends number> = T & { readonly __capacity?: N };
export { copy, equals } from "./model-reactive.ts";
export { capacity as __capacity } from "./model-reactive.ts";
export { frames, after, until, join, all, any, cancel, type Join } from "./model-tasks.ts";
export declare function map<T, U>(value: readonly T[], fn: (value: T, index: i32) => U): U[];
export declare function filter<T>(value: readonly T[], fn: (value: T, index: i32) => boolean): T[];
export declare function find<T>(value: readonly T[], fn: (value: T, index: i32) => boolean): T | undefined;
export declare function some<T>(value: readonly T[], fn: (value: T, index: i32) => boolean): boolean;
import type { i32, f32, f64, Color, u32 } from "./numeric-microts.ts";
export type MicroTsPlainNumber = number & { readonly __type?: never; readonly __newtype?: never };
export type MicroTsNumericResult<T extends number> = T extends MicroTsPlainNumber ? number : T;
export declare function len<T>(value: string | readonly T[]): i32;
export declare function trunc(value: f32 | f64): i32;
export declare function floor(value: f32 | f64): i32;
export declare function ceil(value: f32 | f64): i32;
export declare function round(value: f32 | f64): i32;
export declare function idiv<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function imod<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function min<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function max<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function abs<T extends number>(value: T): MicroTsNumericResult<T>;
export declare function clamp<T extends number>(value: T, other: NoInfer<T> | MicroTsPlainNumber, upper: NoInfer<T> | MicroTsPlainNumber): MicroTsNumericResult<T>;
export declare function fixed(value: f32 | f64, digits: i32): string;
export declare function __colorBits(value: Color): u32;
export declare function __colorText(value: Color | undefined, missing?: string): string;
export declare function __modelNumber(value: number, type: string): number;
export declare function __modelMultiply(left: number, right: number): number;
