// GENERATED by hand-run script: every size/tone pair as a complete Tailwind literal.
// Class strings must exist verbatim in the source, so they cannot be concatenated
// at runtime. Use textClass() instead of composing classes.

export type TextSize = "xs" | "xsb" | "sm" | "base" | "lg" | "hero";
export type TextTone = "ink" | "sub" | "white" | "teal" | "amber" | "coral" | "sky" | "night" | "mist" | "paper";

const TEXT_CLASS: Record<string, string> = {
  "xs:ink": "text-xs text-[#1f3440]",
  "xs:sub": "text-xs text-[#5b7480]",
  "xs:white": "text-xs text-[#ffffff]",
  "xs:teal": "text-xs text-[#1d7974]",
  "xs:amber": "text-xs text-[#ffc857]",
  "xs:coral": "text-xs text-[#ff6f7d]",
  "xs:sky": "text-xs text-[#4fb8e8]",
  "xs:night": "text-xs text-[#0b1622]",
  "xs:mist": "text-xs text-[#9db7c4]",
  "xsb:ink": "text-xs font-bold text-[#1f3440]",
  "xsb:sub": "text-xs font-bold text-[#5b7480]",
  "xsb:white": "text-xs font-bold text-[#ffffff]",
  "xsb:teal": "text-xs font-bold text-[#1d7974]",
  "xsb:amber": "text-xs font-bold text-[#ffc857]",
  "xsb:coral": "text-xs font-bold text-[#ff6f7d]",
  "xsb:sky": "text-xs font-bold text-[#4fb8e8]",
  "xsb:night": "text-xs font-bold text-[#0b1622]",
  "xsb:mist": "text-xs font-bold text-[#9db7c4]",
  // Text the colour of the card behind it: keeps a blank cell non-empty (an empty text node would
  // change the draw list and repaint the whole screen).
  "xsb:paper": "text-xs font-bold text-[#f7fafb]",
  "sm:ink": "text-sm font-bold text-[#1f3440]",
  "sm:sub": "text-sm font-bold text-[#5b7480]",
  "sm:white": "text-sm font-bold text-[#ffffff]",
  "sm:teal": "text-sm font-bold text-[#1d7974]",
  "sm:amber": "text-sm font-bold text-[#ffc857]",
  "sm:coral": "text-sm font-bold text-[#ff6f7d]",
  "sm:sky": "text-sm font-bold text-[#4fb8e8]",
  "sm:night": "text-sm font-bold text-[#0b1622]",
  "sm:mist": "text-sm font-bold text-[#9db7c4]",
  "base:ink": "text-base font-bold text-[#1f3440]",
  "base:sub": "text-base font-bold text-[#5b7480]",
  "base:white": "text-base font-bold text-[#ffffff]",
  "base:teal": "text-base font-bold text-[#1d7974]",
  "base:amber": "text-base font-bold text-[#ffc857]",
  "base:coral": "text-base font-bold text-[#ff6f7d]",
  "base:sky": "text-base font-bold text-[#4fb8e8]",
  "base:night": "text-base font-bold text-[#0b1622]",
  "base:mist": "text-base font-bold text-[#9db7c4]",
  "lg:ink": "text-lg font-bold text-[#1f3440]",
  "lg:sub": "text-lg font-bold text-[#5b7480]",
  "lg:white": "text-lg font-bold text-[#ffffff]",
  "lg:teal": "text-lg font-bold text-[#1d7974]",
  "lg:amber": "text-lg font-bold text-[#ffc857]",
  "lg:coral": "text-lg font-bold text-[#ff6f7d]",
  "lg:sky": "text-lg font-bold text-[#4fb8e8]",
  "lg:night": "text-lg font-bold text-[#0b1622]",
  "lg:mist": "text-lg font-bold text-[#9db7c4]",
  "hero:ink": "text-4xl font-bold text-[#1f3440]",
  "hero:sub": "text-4xl font-bold text-[#5b7480]",
  "hero:white": "text-4xl font-bold text-[#ffffff]",
  "hero:teal": "text-4xl font-bold text-[#1d7974]",
  "hero:amber": "text-4xl font-bold text-[#ffc857]",
  "hero:coral": "text-4xl font-bold text-[#ff6f7d]",
  "hero:sky": "text-4xl font-bold text-[#4fb8e8]",
  "hero:night": "text-4xl font-bold text-[#0b1622]",
  "hero:mist": "text-4xl font-bold text-[#9db7c4]",
};

export function textClass(size: TextSize, tone: TextTone): string {
  return TEXT_CLASS[size + ":" + tone] ?? TEXT_CLASS[size + ":ink"];
}
