// Pocket Retro browser host (Worker side).
// Does the same as the root module generated by pocket-retro tools/build.ts:
//   boot()  = sdkBoot(); setup();
//   frame() = beginFrame(keys, ticks); update(); draw(); endFrame();
// The difference: here Sucrase strips types from the game source and it runs as JavaScript, bypassing MicroTS and Rust.
import { transform } from "sucrase";
import * as std from "@pocketjs/framework/solid/std";
import * as retro from "retro";
import { loadAssets, type BakedAssets } from "retro-sdk/assets";
import { boot as sdkBoot, beginFrame, endFrame } from "retro-sdk/host";
import * as hw from "retro-sdk/hw";
import type { WorkerRequest, WorkerReply, SourceError } from "./protocol";

interface Game {
  setup(): void;
  update(): void;
  draw(): void;
}

const MODULES: Record<string, unknown> = {
  retro,
  "@pocketjs/framework/solid/std": std,
};

let game: Game | null = null;
let lastColors = "";

const post = (msg: WorkerReply, transfer: Transferable[] = []) =>
  (self as unknown as Worker).postMessage(msg, transfer);

// new Function inserts wrapper lines before the body; probe the offset so error line numbers match the editor
const LINE_OFFSET = (() => {
  try {
    new Function("throw new Error('probe')\n//# sourceURL=probe.ts")();
  } catch (e) {
    const m = String((e as Error).stack).match(/probe\.ts:(\d+)/);
    if (m) return Number(m[1]) - 1;
  }
  return 2;
})();

/** sourceURL is project/<path>, used to map errors back to their file */
const SOURCE_PREFIX = "project/";

function locate(error: unknown, phase: SourceError["phase"], file?: string): SourceError {
  const err = error instanceof Error ? error : new Error(String(error));
  const out: SourceError = { phase, message: err.message, stack: err.stack, file };
  // Sucrase syntax errors carry loc; runtime errors use the first project-file frame in the stack
  const loc = (err as Error & { loc?: { line: number; column: number } }).loc;
  if (loc) {
    out.line = loc.line;
    out.column = loc.column + 1;
  } else {
    const m = String(err.stack).match(/project\/([^\s:)]+\.ts):(\d+):(\d+)/);
    if (m) {
      out.file = m[1];
      out.line = Number(m[2]) - LINE_OFFSET;
      out.column = Number(m[3]);
    }
  }
  return out;
}

const format = (v: unknown): string => {
  if (typeof v === "string") return v;
  try {
    return JSON.stringify(v);
  } catch {
    return String(v);
  }
};
const consoleShim = Object.fromEntries(
  (["log", "info", "warn", "error", "debug"] as const).map((level) => [
    level,
    (...args: unknown[]) => post({ type: "log", level, text: args.map(format).join(" ") }),
  ]),
);

function normalize(path: string): string {
  const out: string[] = [];
  for (const part of path.split("/")) {
    if (!part || part === ".") continue;
    if (part === "..") out.pop();
    else out.push(part);
  }
  return out.join("/");
}

/** Project modules run as CommonJS: Sucrase rewrites import to require; relative paths resolve against the project files */
function compile(files: Record<string, string>, entry: string): Game {
  const cache = new Map<string, { exports: Record<string, unknown> }>();
  const load = (path: string): Record<string, unknown> => {
    const cached = cache.get(path);
    if (cached) return cached.exports;
    let code: string;
    try {
      code = transform(files[path]!, { transforms: ["typescript", "imports"], filePath: path }).code;
    } catch (e) {
      throw Object.assign(locate(e, "compile", path), { __located: true });
    }
    const module = { exports: {} as Record<string, unknown> };
    cache.set(path, module);
    const dir = path.includes("/") ? path.slice(0, path.lastIndexOf("/") + 1) : "";
    const require = (name: string) => {
      if (name in MODULES) return MODULES[name];
      if (name.startsWith("./") || name.startsWith("../")) {
        const base = normalize(dir + name);
        const target = [base, base + ".ts", base + "/index.ts"].find((p) => p in files);
        if (target) return load(target);
      }
      throw new Error(`Cannot find module "${name}". The playground provides "retro", "@pocketjs/framework/solid/std" and the project's own .ts files.`);
    };
    const run = new Function("require", "exports", "module", "console", `${code}\n//# sourceURL=${SOURCE_PREFIX}${path}`);
    run(require, module.exports, module, consoleShim);
    return module.exports;
  };
  const g = load(entry) as Partial<Game>;
  for (const name of ["setup", "update", "draw"] as const)
    if (typeof g[name] !== "function") throw new Error(`${entry} must export a function named ${name}()`);
  return g as Game;
}

function colorsIfChanged(): number[] | undefined {
  const key = hw.colors.join(",");
  if (key === lastColors) return undefined;
  lastColors = key;
  return hw.colors.slice();
}

function snapshot(id: number): void {
  const screen = Uint8Array.from(hw.screen);
  const voices = Int32Array.from(hw.voices);
  hw.voices.length = 0;
  post(
    {
      type: "frame",
      id,
      width: hw.width,
      height: hw.height,
      fps: hw.fps,
      screen,
      colors: colorsIfChanged(),
      voices,
    },
    [screen.buffer, voices.buffer],
  );
}

self.onmessage = (event: MessageEvent<WorkerRequest>) => {
  const msg = event.data;
  if (msg.type === "start") {
    try {
      loadAssets(msg.assets as BakedAssets);
      game = compile(msg.files, msg.entry);
    } catch (e) {
      post({ type: "error", error: (e as { __located?: boolean }).__located ? (e as SourceError) : locate(e, "compile", msg.entry) });
      return;
    }
    try {
      sdkBoot();
      game.setup();
    } catch (e) {
      post({ type: "error", error: locate(e, "setup") });
      game = null;
      return;
    }
    if (hw.width <= 0 || hw.height <= 0) {
      post({ type: "error", error: { phase: "setup", message: "setup() must call system.init(width, height) before the first frame" } });
      game = null;
      return;
    }
    post({ type: "ready", width: hw.width, height: hw.height, fps: hw.fps });
    snapshot(0);
  } else if (msg.type === "frame") {
    if (!game) return;
    try {
      beginFrame(msg.keys, msg.ticks);
      game.update();
      game.draw();
      endFrame();
    } catch (e) {
      post({ type: "error", error: locate(e, "frame") });
      game = null;
      return;
    }
    snapshot(msg.id);
  }
};
