// AUTO-GENERATED by apps/nexus-touch/gen-art.ts — do not edit; run `bun apps/nexus-touch/gen-art.ts`.
//
// The baked art of the Pocket Nexus touch scene and the layout the homepage
// chose for a 320x480 screen at density 2. Every image name is a full
// string literal so tools/build.ts bakes it into the pak; the letter metrics
// are the Titan One ink boxes at FS px that the physics bodies are sized from.

import type { LetterArt, Tile } from "./app.tsx";

/** The screen this art is laid out for, logical px. */
export const VIEWPORT = [320, 480] as const;
/** The wordmark's font size: the homepage's fitHero() at 320x480. */
export const FS = 69;

export const LETTER_ART: readonly LetterArt[] = [
  {
    "ch": "P",
    "src": "art/letter-0.png",
    "shadow": "art/shadow-0.png",
    "w": 44.3,
    "ih": 49.68,
    "rcK": 0.26,
    "home": [
      45.96,
      61.11
    ]
  },
  {
    "ch": "O",
    "src": "art/o-body.png",
    "shadow": "art/shadow-1.png",
    "w": 48.71,
    "ih": 50.3,
    "rcK": 0.96,
    "home": [
      95.21,
      57.66
    ]
  },
  {
    "ch": "C",
    "src": "art/letter-2.png",
    "shadow": "art/shadow-2.png",
    "w": 41.12,
    "ih": 50.3,
    "rcK": 0.5,
    "home": [
      142.87,
      60.55
    ]
  },
  {
    "ch": "K",
    "src": "art/letter-3.png",
    "shadow": "art/shadow-3.png",
    "w": 45.13,
    "ih": 50.23,
    "rcK": 0.26,
    "home": [
      188.73,
      58.21
    ]
  },
  {
    "ch": "E",
    "src": "art/letter-4.png",
    "shadow": "art/shadow-4.png",
    "w": 37.26,
    "ih": 48.99,
    "rcK": 0.26,
    "home": [
      232.67,
      61.52
    ]
  },
  {
    "ch": "T",
    "src": "art/letter-5.png",
    "shadow": "art/shadow-5.png",
    "w": 42.16,
    "ih": 48.99,
    "rcK": 0.26,
    "home": [
      275.13,
      58.9
    ]
  },
  {
    "ch": "N",
    "src": "art/letter-6.png",
    "shadow": "art/shadow-6.png",
    "w": 45.13,
    "ih": 48.99,
    "rcK": 0.26,
    "home": [
      68.58,
      114.91
    ]
  },
  {
    "ch": "E",
    "src": "art/letter-7.png",
    "shadow": "art/shadow-7.png",
    "w": 37.26,
    "ih": 48.99,
    "rcK": 0.26,
    "home": [
      112.52,
      118.22
    ]
  },
  {
    "ch": "X",
    "src": "art/letter-8.png",
    "shadow": "art/shadow-8.png",
    "w": 48.37,
    "ih": 48.99,
    "rcK": 0.26,
    "home": [
      158.07,
      115.05
    ]
  },
  {
    "ch": "U",
    "src": "art/letter-9.png",
    "shadow": "art/shadow-9.png",
    "w": 44.57,
    "ih": 49.61,
    "rcK": 0.5,
    "home": [
      207.28,
      117.67
    ]
  },
  {
    "ch": "S",
    "src": "art/letter-10.png",
    "shadow": "art/shadow-10.png",
    "w": 41.68,
    "ih": 50.3,
    "rcK": 0.5,
    "home": [
      253.15,
      114.5
    ]
  }
];

/** The O's face layers over its plain sticker; the eyes are separate nodes. */
export const O_FACE = {
  "look": "art/o-look.png",
  "talk": "art/o-talk.png",
  "happy": "art/o-happy.png",
  "wince": "art/o-wince.png",
  "shut": "art/o-shut.png"
} as const;
export const O_EYE = "art/o-eye.png";
/** Eye centres from the O's centre, px. */
export const O_EYES = {"ex":8.77,"ey":-5.03};

export const TOY_ART = {
  "star": "art/toy-star.png",
  "spark": "art/toy-spark.png",
  "heart": "art/toy-heart.png",
  "cursor": "art/toy-cursor.png",
  "gear": "art/toy-gear.png",
  "bolt": "art/toy-bolt.png",
  "cart": "art/toy-cart.png",
  "planet": "art/toy-planet.png",
  "bubble": "art/toy-bubble.png",
  "dpad": "art/toy-dpad.png",
  "ghost": "art/toy-ghost.png",
  "ball": "art/toy-ball.png",
  "pjs": "art/toy-pjs.png",
  "mystery": "art/toy-mystery.png"
} as const;

export const PARTICLE_ART = {
  "burst": [
    "art/p-burst-y.png",
    "art/p-burst-p.png",
    "art/p-burst-c.png",
    "art/p-burst-l.png",
    "art/p-burst-o.png",
    "art/p-burst-i.png"
  ],
  "bdot": [
    "art/p-bdot-y.png",
    "art/p-bdot-p.png",
    "art/p-bdot-c.png",
    "art/p-bdot-l.png",
    "art/p-bdot-o.png",
    "art/p-bdot-i.png"
  ],
  "star": [
    "art/p-star-y.png",
    "art/p-star-p.png",
    "art/p-star-c.png",
    "art/p-star-l.png",
    "art/p-star-i.png"
  ],
  "dot": [
    "art/p-dot-y.png",
    "art/p-dot-p.png",
    "art/p-dot-c.png",
    "art/p-dot-l.png",
    "art/p-dot-i.png"
  ]
} as const;

export const POCKET_ART = {
  "front": "art/pocket-front.png",
  "mouth": "art/pocket-mouth.png",
  "whites": "art/pocket-whites.png",
  "pupils": "art/pocket-pupils.png",
  "happy": "art/pocket-happy.png"
} as const;

export const SKY_TILES: readonly Tile[] = [
  {
    "src": "art/sky-0-0.png",
    "x": 0,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "src": "art/sky-0-1.png",
    "x": 256,
    "y": 0,
    "w": 64,
    "h": 256
  },
  {
    "src": "art/sky-1-0.png",
    "x": 0,
    "y": 256,
    "w": 256,
    "h": 256
  },
  {
    "src": "art/sky-1-1.png",
    "x": 256,
    "y": 256,
    "w": 64,
    "h": 256
  }
];
export const HAZE_ART = "art/haze.png";
export const HAZE_BOX = {"x":0,"y":-72.39,"w":320,"h":320};
export const GLOW_ART = "art/glow.png";

/** The lede at its homepage position; `ink` is the text's box. */
export const LEDE = {
  "x": 15,
  "y": 157,
  "w": 290,
  "h": 104,
  "ink": {
    "l": 18,
    "t": 159.59,
    "r": 302,
    "b": 256.23
  },
  "tiles": [
    {
      "src": "art/lede-0-0.png",
      "x": 0,
      "y": 0,
      "w": 256,
      "h": 128
    },
    {
      "src": "art/lede-0-1.png",
      "x": 156,
      "y": 0,
      "w": 256,
      "h": 128
    }
  ]
};
export const COPY: Tile = {"src":"art/copy-0-0.png","x":18,"y":446,"w":256,"h":32};
export const HINT = {
  "text": {
    "src": "art/hint-text-0-0.png",
    "x": 102,
    "y": 247,
    "w": 128,
    "h": 64
  },
  "arrow": {
    "src": "art/hint-arrow-0-0.png",
    "x": 149,
    "y": 269,
    "w": 64,
    "h": 64
  }
};

/** Speech bubbles; (px, py) is the anchor the tail points at. */
export const TAG_ART = {
  "pjs": {
    "src": "art/tag-pjs.png",
    "w": 128,
    "h": 64,
    "px": 64,
    "py": 53
  },
  "say": {
    "Shh.": {
      "src": "art/say-shh.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Not yet.": {
      "src": "art/say-not-yet.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Soon.": {
      "src": "art/say-soon.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Sealed.": {
      "src": "art/say-sealed.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Still cooking.": {
      "src": "art/say-still-cooking.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "?": {
      "src": "art/say-q.png",
      "w": 64,
      "h": 64,
      "px": 32,
      "py": 53
    }
  },
  "perchR": {
    "Shh.": {
      "src": "art/say-shh-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Not yet.": {
      "src": "art/say-not-yet-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Soon.": {
      "src": "art/say-soon-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Sealed.": {
      "src": "art/say-sealed-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Still cooking.": {
      "src": "art/say-still-cooking-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "?": {
      "src": "art/say-q-r.png",
      "w": 64,
      "h": 64,
      "px": 4,
      "py": 32
    }
  },
  "perchL": {
    "Shh.": {
      "src": "art/say-shh-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Not yet.": {
      "src": "art/say-not-yet-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Soon.": {
      "src": "art/say-soon-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Sealed.": {
      "src": "art/say-sealed-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Still cooking.": {
      "src": "art/say-still-cooking-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "?": {
      "src": "art/say-q-l.png",
      "w": 64,
      "h": 64,
      "px": 60,
      "py": 32
    }
  }
};
