// AUTO-GENERATED by apps/nexus-touch/gen-art.ts — do not edit; run `bun apps/nexus-touch/gen-art.ts`.
//
// The baked art of the Pocket Nexus touch scene and the layout the homepage
// chose for a 360x640 screen at density 1. Every image name is a full
// string literal so tools/build.ts bakes it into the pak; the letter metrics
// are the Titan One ink boxes at FS px that the physics bodies are sized from.

import type { LetterArt, Tile } from "../app.tsx";

/** The screen this art is laid out for, logical px. */
export const VIEWPORT = [360, 640] as const;
/** The wordmark's font size: the homepage's fitHero() at 360x640. */
export const FS = 79;

export const LETTER_ART: readonly LetterArt[] = [
  {
    "ch": "P",
    "src": "art/letter-0.png",
    "shadow": "art/shadow-0.png",
    "w": 50.72,
    "ih": 56.88,
    "rcK": 0.26,
    "home": [
      49.4,
      124.91
    ]
  },
  {
    "ch": "O",
    "src": "art/o-body.png",
    "shadow": "art/shadow-1.png",
    "w": 55.77,
    "ih": 57.59,
    "rcK": 0.96,
    "home": [
      105.79,
      120.96
    ]
  },
  {
    "ch": "C",
    "src": "art/letter-2.png",
    "shadow": "art/shadow-2.png",
    "w": 47.08,
    "ih": 57.59,
    "rcK": 0.5,
    "home": [
      160.37,
      124.28
    ]
  },
  {
    "ch": "K",
    "src": "art/letter-3.png",
    "shadow": "art/shadow-3.png",
    "w": 51.67,
    "ih": 57.51,
    "rcK": 0.26,
    "home": [
      212.89,
      121.59
    ]
  },
  {
    "ch": "E",
    "src": "art/letter-4.png",
    "shadow": "art/shadow-4.png",
    "w": 42.66,
    "ih": 56.09,
    "rcK": 0.26,
    "home": [
      263.2,
      125.38
    ]
  },
  {
    "ch": "T",
    "src": "art/letter-5.png",
    "shadow": "art/shadow-5.png",
    "w": 48.27,
    "ih": 56.09,
    "rcK": 0.26,
    "home": [
      311.82,
      122.38
    ]
  },
  {
    "ch": "N",
    "src": "art/letter-6.png",
    "shadow": "art/shadow-6.png",
    "w": 51.67,
    "ih": 56.09,
    "rcK": 0.26,
    "home": [
      75.3,
      186.51
    ]
  },
  {
    "ch": "E",
    "src": "art/letter-7.png",
    "shadow": "art/shadow-7.png",
    "w": 42.66,
    "ih": 56.09,
    "rcK": 0.26,
    "home": [
      125.61,
      190.31
    ]
  },
  {
    "ch": "X",
    "src": "art/letter-8.png",
    "shadow": "art/shadow-8.png",
    "w": 55.38,
    "ih": 56.09,
    "rcK": 0.26,
    "home": [
      177.78,
      186.67
    ]
  },
  {
    "ch": "U",
    "src": "art/letter-9.png",
    "shadow": "art/shadow-9.png",
    "w": 51.03,
    "ih": 56.8,
    "rcK": 0.5,
    "home": [
      234.14,
      189.67
    ]
  },
  {
    "ch": "S",
    "src": "art/letter-10.png",
    "shadow": "art/shadow-10.png",
    "w": 47.72,
    "ih": 57.59,
    "rcK": 0.5,
    "home": [
      286.66,
      186.04
    ]
  }
];

/** The O's face layers over its plain sticker; the eyes are separate nodes. */
export const O_FACE = {
  "look": "art/o-look.png",
  "talk": "art/o-talk.png",
  "happy": "art/o-happy.png",
  "wince": "art/o-wince.png",
  "shut": "art/o-shut.png"
} as const;
export const O_EYE = "art/o-eye.png";
/** Eye centres from the O's centre, px. */
export const O_EYES = {"ex":10.04,"ey":-5.76};

export const TOY_ART = {
  "star": "art/toy-star.png",
  "spark": "art/toy-spark.png",
  "heart": "art/toy-heart.png",
  "cursor": "art/toy-cursor.png",
  "gear": "art/toy-gear.png",
  "bolt": "art/toy-bolt.png",
  "cart": "art/toy-cart.png",
  "planet": "art/toy-planet.png",
  "bubble": "art/toy-bubble.png",
  "dpad": "art/toy-dpad.png",
  "ghost": "art/toy-ghost.png",
  "ball": "art/toy-ball.png",
  "pjs": "art/toy-pjs.png",
  "mystery": "art/toy-mystery.png"
} as const;

export const PARTICLE_ART = {
  "burst": [
    "art/p-burst-y.png",
    "art/p-burst-p.png",
    "art/p-burst-c.png",
    "art/p-burst-l.png",
    "art/p-burst-o.png",
    "art/p-burst-i.png"
  ],
  "bdot": [
    "art/p-bdot-y.png",
    "art/p-bdot-p.png",
    "art/p-bdot-c.png",
    "art/p-bdot-l.png",
    "art/p-bdot-o.png",
    "art/p-bdot-i.png"
  ],
  "star": [
    "art/p-star-y.png",
    "art/p-star-p.png",
    "art/p-star-c.png",
    "art/p-star-l.png",
    "art/p-star-i.png"
  ],
  "dot": [
    "art/p-dot-y.png",
    "art/p-dot-p.png",
    "art/p-dot-c.png",
    "art/p-dot-l.png",
    "art/p-dot-i.png"
  ]
} as const;

export const POCKET_ART = {
  "front": "art/pocket-front.png",
  "mouth": "art/pocket-mouth.png",
  "whites": "art/pocket-whites.png",
  "pupils": "art/pocket-pupils.png",
  "happy": "art/pocket-happy.png"
} as const;

export const SKY_TILES: readonly Tile[] = [
  {
    "src": "art/sky-0-0.png",
    "x": 0,
    "y": 0,
    "w": 512,
    "h": 512
  },
  {
    "src": "art/sky-1-0.png",
    "x": 0,
    "y": 512,
    "w": 512,
    "h": 128
  }
];
export const HAZE_ART = "art/haze.png";
export const HAZE_BOX = {"x":0,"y":-24.74,"w":360,"h":360};
export const GLOW_ART = "art/glow.png";

/** The lede at its homepage position; `ink` is the text's box. */
export const LEDE = {
  "x": 15,
  "y": 236,
  "w": 330,
  "h": 81,
  "ink": {
    "l": 18,
    "t": 238.63,
    "r": 342,
    "b": 312.02
  },
  "tiles": [
    {
      "src": "art/lede-0-0.png",
      "x": 0,
      "y": 0,
      "w": 512,
      "h": 128
    }
  ]
};
export const COPY: Tile = {"src":"art/copy-0-0.png","x":18,"y":606,"w":256,"h":32};
export const HINT = {
  "text": {
    "src": "art/hint-text-0-0.png",
    "x": 122,
    "y": 374,
    "w": 128,
    "h": 64
  },
  "arrow": {
    "src": "art/hint-arrow-0-0.png",
    "x": 169,
    "y": 396,
    "w": 64,
    "h": 64
  }
};

/** Speech bubbles; (px, py) is the anchor the tail points at. */
export const TAG_ART = {
  "pjs": {
    "src": "art/tag-pjs.png",
    "w": 128,
    "h": 64,
    "px": 64,
    "py": 53
  },
  "say": {
    "Shh.": {
      "src": "art/say-shh.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Not yet.": {
      "src": "art/say-not-yet.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Soon.": {
      "src": "art/say-soon.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Sealed.": {
      "src": "art/say-sealed.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "Still cooking.": {
      "src": "art/say-still-cooking.png",
      "w": 128,
      "h": 64,
      "px": 64,
      "py": 53
    },
    "?": {
      "src": "art/say-q.png",
      "w": 64,
      "h": 64,
      "px": 32,
      "py": 53
    }
  },
  "perchR": {
    "Shh.": {
      "src": "art/say-shh-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Not yet.": {
      "src": "art/say-not-yet-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Soon.": {
      "src": "art/say-soon-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Sealed.": {
      "src": "art/say-sealed-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "Still cooking.": {
      "src": "art/say-still-cooking-r.png",
      "w": 128,
      "h": 64,
      "px": 4,
      "py": 32
    },
    "?": {
      "src": "art/say-q-r.png",
      "w": 64,
      "h": 64,
      "px": 4,
      "py": 32
    }
  },
  "perchL": {
    "Shh.": {
      "src": "art/say-shh-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Not yet.": {
      "src": "art/say-not-yet-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Soon.": {
      "src": "art/say-soon-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Sealed.": {
      "src": "art/say-sealed-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "Still cooking.": {
      "src": "art/say-still-cooking-l.png",
      "w": 128,
      "h": 64,
      "px": 124,
      "py": 32
    },
    "?": {
      "src": "art/say-q-l.png",
      "w": 64,
      "h": 64,
      "px": 60,
      "py": 32
    }
  }
};
