// AUTO-GENERATED by apps/nexus/gen-art.ts — do not edit; run `bun apps/nexus/gen-art.ts`.
//
// The baked art of the Pocket Nexus scene. Every image name is a full string
// literal so tools/build.ts bakes it into the pak; the letter metrics are the
// Titan One ink boxes at FS px that the physics bodies are sized from.

export interface LetterArt { ch: string; src: string; shadow: string; w: number; ih: number; rcK: number }

export const LETTER_ART: readonly LetterArt[] = [
  {
    "ch": "P",
    "src": "art/letter-0.png",
    "shadow": "art/shadow-0.png",
    "w": 46.22,
    "ih": 51.84,
    "rcK": 0.26
  },
  {
    "ch": "O",
    "src": "art/o-open.png",
    "shadow": "art/shadow-1.png",
    "w": 50.83,
    "ih": 52.49,
    "rcK": 0.96
  },
  {
    "ch": "C",
    "src": "art/letter-2.png",
    "shadow": "art/shadow-2.png",
    "w": 42.91,
    "ih": 52.49,
    "rcK": 0.5
  },
  {
    "ch": "K",
    "src": "art/letter-3.png",
    "shadow": "art/shadow-3.png",
    "w": 47.09,
    "ih": 52.42,
    "rcK": 0.26
  },
  {
    "ch": "E",
    "src": "art/letter-4.png",
    "shadow": "art/shadow-4.png",
    "w": 38.88,
    "ih": 51.12,
    "rcK": 0.26
  },
  {
    "ch": "T",
    "src": "art/letter-5.png",
    "shadow": "art/shadow-5.png",
    "w": 43.99,
    "ih": 51.12,
    "rcK": 0.26
  },
  {
    "ch": "N",
    "src": "art/letter-6.png",
    "shadow": "art/shadow-6.png",
    "w": 47.09,
    "ih": 51.12,
    "rcK": 0.26
  },
  {
    "ch": "E",
    "src": "art/letter-7.png",
    "shadow": "art/shadow-7.png",
    "w": 38.88,
    "ih": 51.12,
    "rcK": 0.26
  },
  {
    "ch": "X",
    "src": "art/letter-8.png",
    "shadow": "art/shadow-8.png",
    "w": 50.47,
    "ih": 51.12,
    "rcK": 0.26
  },
  {
    "ch": "U",
    "src": "art/letter-9.png",
    "shadow": "art/shadow-9.png",
    "w": 46.51,
    "ih": 51.77,
    "rcK": 0.5
  },
  {
    "ch": "S",
    "src": "art/letter-10.png",
    "shadow": "art/shadow-10.png",
    "w": 43.49,
    "ih": 52.49,
    "rcK": 0.5
  }
];

export const O_FACE = {
  "open": "art/o-open.png",
  "shut": "art/o-shut.png",
  "left": "art/o-left.png",
  "right": "art/o-right.png",
  "blink": "art/o-blink.png",
  "happy": "art/o-happy.png",
  "wince": "art/o-wince.png"
} as const;

export const TOY_ART = {
  "star": "art/toy-star.png",
  "spark": "art/toy-spark.png",
  "heart": "art/toy-heart.png",
  "cursor": "art/toy-cursor.png",
  "gear": "art/toy-gear.png",
  "bolt": "art/toy-bolt.png",
  "cart": "art/toy-cart.png",
  "planet": "art/toy-planet.png",
  "bubble": "art/toy-bubble.png",
  "dpad": "art/toy-dpad.png",
  "ghost": "art/toy-ghost.png",
  "ball": "art/toy-ball.png",
  "pjs": "art/toy-pjs.png",
  "mystery": "art/toy-mystery.png"
} as const;

export const PARTICLE_ART = {
  "burst": [
    "art/p-burst-y.png",
    "art/p-burst-p.png",
    "art/p-burst-c.png",
    "art/p-burst-l.png",
    "art/p-burst-o.png",
    "art/p-burst-i.png"
  ],
  "bdot": [
    "art/p-bdot-y.png",
    "art/p-bdot-p.png",
    "art/p-bdot-c.png",
    "art/p-bdot-l.png",
    "art/p-bdot-o.png",
    "art/p-bdot-i.png"
  ],
  "star": [
    "art/p-star-y.png",
    "art/p-star-p.png",
    "art/p-star-c.png",
    "art/p-star-l.png",
    "art/p-star-i.png"
  ],
  "dot": [
    "art/p-dot-y.png",
    "art/p-dot-p.png",
    "art/p-dot-c.png",
    "art/p-dot-l.png",
    "art/p-dot-i.png"
  ]
} as const;

export const POCKET_ART = {
  "front": "art/pocket-front.png",
  "mouth": "art/pocket-mouth.png",
  "eyes": "art/pocket-eyes.png",
  "happy": "art/pocket-eyes-happy.png"
} as const;

export const BACKDROP_ART = {
  "top": "art/top.png",
  "haze": "art/haze.png",
  "bottom": "art/bottom.png",
  "glow": "art/glow.png"
} as const;

export const HINT_ART = "art/hint.png";
export const COPY_ART = "art/copy.png";
export const LEDE_ART = "art/lede.png";
/** The lede's ink box inside its 512x64 sprite. */
export const LEDE_BOX = {"l":78,"t":1,"r":434,"b":54.09};
/** The wordmark block measured from the metrics above. */
export const WORD_BOX = {"w":284.32,"h":112.18,"rowH":52.49};
