//! Table-driven sprite presenter. `assets.rs` (generated by hosts/gba/assets.ts
//! from the compiler's layer plan and the native bake) lists one `Layer` per
//! dynamic subtree: its crop, sprite grid, OAM slots, OBJ VRAM and frames.
//! Each frame the presenter reads every layer's state back from the retained
//! core — mounted branch signatures, a formula leaf's rect, a resolved color,
//! the text run — picks the frame, uploads it when it changed, and places the
//! sprites at the crop origin plus the root's translate.

use microts::{NodeId, Ui};
use pocketjs_gba::video::{Background, OamBuffer, Presenter, Sprite, SpriteShape};

/// One sprite layer (see hosts/gba/assets.ts for the field contract).
pub struct Layer {
    pub name: &'static str,
    /// 0 branches, 1 opacity, 2 size, 3 color, 4 text.
    pub kind: u8,
    /// Absolute crop [x, y, w, h] the frames were baked for.
    pub crop: [i16; 4],
    /// 0 wide 32x16 objects, 1 tall 16x32 objects.
    pub shape: u8,
    pub columns: u8,
    pub rows: u8,
    pub oam_first: u8,
    /// Halfword offset of this layer's resident frame(s) in OBJ VRAM.
    pub vram_words: u16,
    pub translate: bool,
    /// Child index path from the layer root to the probed node.
    pub node: &'static [u8],
    pub frames: &'static [&'static [u16]],
    /// Per frame: size value, color bits, or glyph code point.
    pub keys: &'static [u32],
    pub styles: &'static [i32],
    pub assets: &'static [&'static str],
    pub texts: &'static [&'static str],
    /// Quarter-pixel glyph advances, per frame (text layers).
    pub advances: &'static [i16],
    /// Static run prefix the background already shows (text layers).
    pub prefix: &'static str,
    pub prefix_advance: i16,
    pub max_glyphs: u8,
    /// 0 width, 1 height (size layers).
    pub axis: u8,
    pub range_low: i32,
}

pub mod art {
    use super::Layer;
    include!(concat!(env!("GBA_GENERATED"), "/assets.rs"));
}

pub const KIND_BRANCHES: u8 = 0;
pub const KIND_OPACITY: u8 = 1;
pub const KIND_SIZE: u8 = 2;
pub const KIND_COLOR: u8 = 3;
pub const KIND_TEXT: u8 = 4;

/// Hidden layer or no matching state.
const NONE: usize = usize::MAX;

pub struct Scene {
    presenter: Presenter,
    oam: OamBuffer,
    /// Layer root and probed node ids, in `art::LAYERS` order.
    roots: [NodeId; art::LAYERS.len()],
    probes: [NodeId; art::LAYERS.len()],
    /// Frame resident in each layer's VRAM slot (text layers keep all).
    resident: [usize; art::LAYERS.len()],
    /// Frame chosen this update (NONE = hidden).
    chosen: [usize; art::LAYERS.len()],
    /// Last published state value per layer (diagnostic words).
    pub state: [u32; art::LAYERS.len()],
    /// A branches layer matched no frame or more than one.
    pub faults: u32,
}

fn find(ui: &Ui, node: i32, name: &str) -> Option<NodeId> {
    let id = NodeId(node);
    if ui.debug_name(id) == Some(name) {
        return Some(id);
    }
    ui.core()
        .node_children(node)
        .iter()
        .find_map(|child| find(ui, *child, name))
}

impl Scene {
    /// Find every layer's nodes in the mounted tree and bring up the display.
    ///
    /// # Safety
    /// Call once during forced blank with exclusive access to DMA3 and OAM.
    pub unsafe fn new(ui: &Ui) -> Self {
        const _: () = assert!(art::OBJ_VRAM_WORDS * 2 <= pocketjs_gba::video::OBJ_TILE_BYTES);
        const _: () = assert!(art::OAM_SLOTS_USED <= pocketjs_gba::video::OAM_SLOTS);
        let mut presenter = Presenter::initialize(
            &Background {
                palette: &art::BG_PALETTE,
                tiles: &art::BG_TILES,
                map: &art::BG_MAP,
            },
            &art::OBJ_PALETTE,
        )
        .unwrap();
        let mut roots = [NodeId::NONE; art::LAYERS.len()];
        let mut probes = [NodeId::NONE; art::LAYERS.len()];
        for (index, layer) in art::LAYERS.iter().enumerate() {
            let root = find(ui, NodeId::ROOT.0, layer.name).unwrap();
            let mut probe = root;
            for &step in layer.node {
                probe = NodeId(ui.core().node_children(probe.0)[usize::from(step)]);
            }
            roots[index] = root;
            probes[index] = probe;
            if layer.kind == KIND_TEXT {
                // Glyph tiles stay resident; sprites select them by tile index.
                let frame_words = layer.frames.first().map_or(0, |frame| frame.len());
                for (i, frame) in layer.frames.iter().enumerate() {
                    presenter
                        .upload_obj_tiles(usize::from(layer.vram_words) + i * frame_words, frame)
                        .unwrap();
                }
            }
        }
        Self {
            presenter,
            oam: OamBuffer::new(),
            roots,
            probes,
            resident: [NONE; art::LAYERS.len()],
            chosen: [NONE; art::LAYERS.len()],
            state: [0; art::LAYERS.len()],
            faults: 0,
        }
    }

    fn shape(layer: &Layer) -> SpriteShape {
        if layer.shape == 1 {
            SpriteShape::Tall16x32
        } else {
            SpriteShape::Wide32x16
        }
    }

    /// Hardware tile index of frame `frame` of `layer` (32-byte units).
    fn tile_index(layer: &Layer, frame: usize) -> u16 {
        let frame_words = layer.frames.first().map_or(0, |f| f.len());
        ((usize::from(layer.vram_words) + frame * frame_words) / 16) as u16
    }

    /// Read every layer's state from the core and build the OAM shadow.
    /// Uploads happen in `present`, during VBlank.
    pub fn update(&mut self, ui: &Ui) {
        let core = ui.core();
        for (index, layer) in art::LAYERS.iter().enumerate() {
            let root = self.roots[index];
            let probe = self.probes[index];
            let style = core.resolved_style(root.0).unwrap();
            let (dx, dy) = if layer.translate { (style.translate_x as i32, style.translate_y as i32) } else { (0, 0) };
            let origin = (i32::from(layer.crop[0]) + dx, i32::from(layer.crop[1]) + dy);
            let shape = Self::shape(layer);
            let objects = usize::from(layer.columns) * usize::from(layer.rows);
            let first = usize::from(layer.oam_first);
            let mut chosen = NONE;
            match layer.kind {
                KIND_BRANCHES => {
                    let mut matches = 0;
                    for &child in core.node_children(root.0) {
                        let node = NodeId(child);
                        let child_style = core.node_style(child).unwrap_or(-1);
                        let asset = ui.image_asset(node).unwrap_or("");
                        let text = core.node_text(child).unwrap_or("");
                        for (frame, &candidate) in layer.styles.iter().enumerate() {
                            if candidate == child_style
                                && (layer.assets[frame].is_empty() || layer.assets[frame] == asset)
                                && (layer.texts[frame].is_empty() || layer.texts[frame] == text)
                            {
                                if matches == 0 {
                                    chosen = frame;
                                }
                                matches += 1;
                                break;
                            }
                        }
                    }
                    if matches > 1 {
                        self.faults = self.faults.wrapping_add(1);
                    }
                    self.state[index] = chosen as u32;
                }
                KIND_OPACITY => {
                    chosen = if style.opacity > 0.5 { 0 } else { NONE };
                    self.state[index] = u32::from(chosen != NONE);
                }
                KIND_SIZE => {
                    let (_, _, w, h) = core.layout_of(probe.0).unwrap();
                    let value = if layer.axis == 1 { h } else { w };
                    let value = (value + 0.5) as i32;
                    let slot = (value - layer.range_low).clamp(0, layer.frames.len() as i32 - 1);
                    chosen = slot as usize;
                    self.state[index] = value as u32;
                }
                KIND_COLOR => {
                    let color = core.resolved_style(probe.0).unwrap().bg_color;
                    chosen = layer
                        .keys
                        .iter()
                        .enumerate()
                        .min_by_key(|(_, &sample)| {
                            [0, 8, 16]
                                .iter()
                                .map(|shift| {
                                    let d = ((color >> shift) & 255) as i32 - ((sample >> shift) & 255) as i32;
                                    d * d
                                })
                                .sum::<i32>()
                        })
                        .map_or(NONE, |(frame, _)| frame);
                    self.state[index] = color;
                }
                KIND_TEXT => {
                    // One object per glyph of the dynamic tail, advanced in quarter pixels.
                    let text = core.node_text(probe.0).unwrap_or("");
                    let tail = text.strip_prefix(layer.prefix).unwrap_or(text);
                    let mut x = origin.0 * 4 + i32::from(layer.prefix_advance);
                    let mut placed = 0;
                    for glyph in tail.chars() {
                        if placed >= usize::from(layer.max_glyphs) {
                            break;
                        }
                        let Some(frame) = layer.keys.iter().position(|&key| key == glyph as u32) else {
                            continue;
                        };
                        self.oam
                            .set_patch(
                                first + placed * objects,
                                Sprite {
                                    x: ((x + 2) / 4) as i16,
                                    y: origin.1 as i16,
                                    shape,
                                    tile_index: Self::tile_index(layer, frame),
                                    priority: 0,
                                },
                                layer.crop[2] as u16,
                                layer.crop[3] as u16,
                            )
                            .unwrap();
                        x += i32::from(layer.advances[frame]);
                        placed += 1;
                    }
                    for slot in placed * objects..usize::from(layer.max_glyphs) * objects {
                        self.oam.hide(first + slot).unwrap();
                    }
                    self.state[index] = placed as u32;
                    self.chosen[index] = NONE;
                    continue;
                }
                _ => {}
            }
            self.chosen[index] = chosen;
            if chosen == NONE || origin.0 >= 240 || origin.0 + i32::from(layer.crop[2]) <= 0 {
                for slot in 0..objects {
                    self.oam.hide(first + slot).unwrap();
                }
                continue;
            }
            self.oam
                .set_patch(
                    first,
                    Sprite {
                        x: origin.0 as i16,
                        y: origin.1 as i16,
                        shape,
                        tile_index: Self::tile_index(layer, 0),
                        priority: 0,
                    },
                    layer.crop[2] as u16,
                    layer.crop[3] as u16,
                )
                .unwrap();
        }
    }

    /// Upload changed frames and the dirty OAM range. Returns DMA bytes.
    ///
    /// # Safety
    /// Call during VBlank with exclusive access to DMA3 and OAM.
    pub unsafe fn present(&mut self) -> usize {
        let mut bytes = 0;
        for (index, layer) in art::LAYERS.iter().enumerate() {
            let chosen = self.chosen[index];
            if layer.kind == KIND_TEXT || chosen == NONE || chosen == self.resident[index] {
                continue;
            }
            bytes += self
                .presenter
                .upload_obj_tiles(usize::from(layer.vram_words), layer.frames[chosen])
                .unwrap();
            self.resident[index] = chosen;
        }
        bytes += self.presenter.present(&mut self.oam);
        self.presenter.enable();
        bytes
    }
}
